# Generated by Django 3.0.1 on 2020-07-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
