# Generated by Django 3.0.1 on 2020-07-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
